---
  - name: Create replicator user
    community.postgresql.postgresql_user:
      name: replicator
      role_attr_flags: REPLICATION
      password: "Otus2022!"
    environment:
      PGOPTIONS: "-c password_encryption=scram-sha-256"
  - name: Create barman user
    community.postgresql.postgresql_user:
      name: barman
      role_attr_flags: SUPERUSER
      password: "Otus2022!"
    environment:
      PGOPTIONS: "-c password_encryption=scram-sha-256"
  - name: Create DB otus
    community.postgresql.postgresql_db:
      name: otus
      encoding: UTF-8
      template: template0    
  - name: Create table in DB otus
    community.postgresql.postgresql_table:
      db: otus
      name: test
      columns:
      - id int
      - name varchar
  - name: Insert data to table
    community.postgresql.postgresql_query:
      db: otus
      query: INSERT INTO test (id, name) VALUES (1, 'alex');
